In [1]:
# Add needed libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

# Preprocessing
from sklearn.preprocessing import OneHotEncoder

# VIF for multi-collinearity detection
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Models and modeling tools
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import statsmodels.api as sm

# Models and modeling tools
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline

# Change inline plots default size
plt.rcParams['figure.figsize'] = [14, 10]

In [11]:
# Read in the rawData
rawData = pd.read_csv('term-deposit-marketing-2020.csv')


# Separate data in independent (features) and dependent (target) datasets
features = rawData.copy()
target = features.pop('y')


# Replace binary columns 1/0
for col in ['default', 'housing', 'loan']:
    features[col].replace({'yes':1,'no':0}, inplace=True)

    
# Encode small categorical columns
cols = ['marital', 'education', 'contact']

enc = OneHotEncoder(sparse=False, dtype=int)
encoded = enc.fit_transform(features[cols])

# There has got to be a better way to do this...
encNames = enc.get_feature_names()
for index, item in enumerate(encNames):
    for i in range(len(cols)):
        encNames[index] = encNames[index].replace('x' + str(i), cols[i])

encDF = pd.DataFrame(encoded)
encDF.columns = encNames

features = features.drop(columns=cols)
features = pd.concat([features, encDF], axis=1)


# Encode large categorical columns
cols = ['month', 'job']

enc = OneHotEncoder(sparse=False, dtype=int)
encoded = enc.fit_transform(features[cols])

# There has got to be a better way to do this...
encNames = enc.get_feature_names()
for index, item in enumerate(encNames):
    for i in range(len(cols)):
        encNames[index] = encNames[index].replace('x' + str(i), cols[i])

encDF = pd.DataFrame(encoded)
encDF.columns = encNames

features = features.drop(columns=cols)
features = pd.concat([features, encDF], axis=1)


# Remove duration (this is not a reasonable thing to have in the model as it should tell success/failure well?)
#features = features.drop(columns=['duration'])

In [14]:
oversample = SMOTE()
ovFeatures, ovTarget = oversample.fit_resample(features, target)

In [17]:
## Look at Mutual Information metric to assess weak relationships between features and target
from sklearn.feature_selection import mutual_info_classif

def make_mi_scores(X, y):
    mi_scores = mutual_info_classif(X, y, discrete_features=True)
    mi_scores = pd.Series(mi_scores, name="MI Scores", index=X.columns)
    mi_scores = mi_scores.sort_values(ascending=False)
    return mi_scores

mi_scores = make_mi_scores(ovFeatures, np.ravel(ovTarget))
display (mi_scores)

duration               0.265438
balance                0.107446
contact_unknown        0.071876
marital_married        0.057423
housing                0.048736
month_may              0.045916
job_blue-collar        0.038855
education_secondary    0.036857
loan                   0.031643
education_primary      0.031251
day                    0.025764
job_technician         0.025348
month_aug              0.025161
month_jul              0.024150
month_jun              0.022122
job_management         0.019505
job_services           0.019485
month_nov              0.016413
campaign               0.016222
job_admin              0.016129
marital_divorced       0.015896
education_tertiary     0.011221
age                    0.011060
contact_telephone      0.010104
marital_single         0.009640
month_jan              0.008653
education_unknown      0.008025
job_entrepreneur       0.007848
job_housemaid          0.006855
job_self-employed      0.006651
job_unemployed         0.005458
month_feb              0.005300
job_retired            0.004181
default                0.003216
job_unknown            0.001376
job_student            0.001242
month_apr              0.000699
month_mar              0.000350
month_oct              0.000141
month_dec              0.000074
contact_cellular       0.000011
Name: MI Scores, dtype: float64

In [18]:
# Look at the skewness of independent variables
features.skew()

age                     0.436080
default                 6.816736
balance                 8.259236
housing                -0.411561
loan                    1.726785
day                     0.067930
duration                3.165307
campaign                4.730901
marital_divorced        2.366427
marital_married        -0.449560
marital_single          1.023505
education_primary       1.888317
education_secondary    -0.099426
education_tertiary      0.979166
education_unknown       4.813341
contact_cellular       -0.506959
contact_telephone       3.781087
contact_unknown         0.776088
month_apr               3.433729
month_aug               2.195556
month_dec              55.445054
month_feb               3.805730
month_jan               5.571914
month_jul               1.860005
month_jun               2.363085
month_mar              12.331125
month_may               0.683557
month_nov               2.866486
month_oct              22.294378
job_admin               2.459527
job_blue-collar         1.252841
job_entrepreneur        5.050551
job_housemaid           5.816270
job_management          1.468005
job_retired             4.987474
job_self-employed       5.032603
job_services            2.709072
job_student             8.564733
job_technician          1.744892
job_unemployed          5.767388
job_unknown            12.931791
dtype: float64

In [19]:
# Look at the correlations between independent variables
features.corr()

,age,default,balance,housing,loan,day,duration,campaign,marital_divorced,marital_married,...,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown
age,1.000000,-0.014857,0.081517,-0.179606,0.000041,-0.011689,-0.036270,0.016204,0.161989,0.265630,...,0.027956,0.084920,-0.005302,0.333164,0.001712,-0.057227,-0.155146,-0.058308,0.008052,0.043904
default,-0.014857,1.000000,-0.070069,-0.019229,0.075006,0.006287,-0.008597,0.012135,0.016748,-0.016458,...,0.025645,0.000017,-0.000951,-0.003878,0.004233,-0.003038,-0.013429,-0.004516,0.007232,-0.006397
balance,0.081517,-0.070069,1.000000,-0.049946,-0.080596,0.011662,0.014072,-0.008137,-0.025910,0.023683,...,0.011692,0.003044,0.072172,0.015917,0.015771,-0.033618,0.000575,-0.012655,0.010020,0.010672
housing,-0.179606,-0.019229,-0.049946,1.000000,0.004266,-0.050622,0.022455,-0.054823,-0.004691,0.000680,...,0.003303,-0.086038,-0.067999,-0.112274,-0.032204,0.062391,-0.034034,-0.032180,-0.046197,-0.077605
loan,0.000041,0.075006,-0.080596,0.004266,1.000000,0.005838,-0.003952,0.000582,0.015635,0.032651,...,0.038244,-0.016788,-0.037817,0.017406,-0.008934,0.031939,-0.047512,0.008396,-0.035591,-0.031734
day,-0.011689,0.006287,0.011662,-0.050622,0.005838,1.000000,-0.032983,0.165429,-0.004055,0.005243,...,-0.003629,0.005355,0.026526,-0.002787,0.005080,-0.009461,-0.011183,0.031902,-0.005475,-0.009526
duration,-0.036270,-0.008597,0.014072,0.022455,-0.003952,-0.032983,1.000000,-0.088387,0.007237,-0.029153,...,0.000247,-0.007239,-0.010846,0.001675,0.008821,0.003569,-0.007175,-0.008469,0.017896,-0.007971
campaign,0.016204,0.012135,-0.008137,-0.054823,0.000582,0.165429,-0.088387,1.000000,-0.019951,0.027962,...,-0.002619,0.002804,0.021105,-0.013881,0.004581,-0.010404,-0.008503,0.018915,-0.017052,0.017037
marital_divorced,0.161989,0.016748,-0.025910,-0.004691,0.015635,-0.004055,0.007237,-0.019951,1.000000,-0.457384,...,-0.000406,0.015053,0.010260,0.042143,-0.018049,0.018813,-0.039441,0.013693,0.008317,-0.012932
marital_married,0.265630,-0.016458,0.023683,0.000680,0.032651,0.005243,-0.029153,0.027962,-0.457384,1.000000,...,0.044941,0.046431,-0.036540,0.056708,0.015806,-0.015312,-0.125955,-0.073221,-0.011904,0.014573
marital_single,-0.408589,0.005893,-0.007168,0.002656,-0.047122,-0.002806,0.026703,-0.016179,-0.223837,-0.764326,...,-0.048960,-0.061803,0.032608,-0.092710,-0.004236,0.003140,0.166645,0.070320,0.007016,-0.006595
education_primary,0.177944,-0.000885,-0.020949,0.011533,-0.012951,-0.029240,-0.007313,0.004326,-0.018886,0.142860,...,-0.016522,0.162660,-0.171793,0.095975,-0.034498,-0.064113,-0.038788,-0.169011,0.023903,0.007346
education_secondary,-0.095671,0.011528,-0.063920,0.093628,0.065472,-0.010139,0.006765,-0.027133,0.020816,-0.024463,...,-0.062648,-0.069426,-0.403486,-0.024257,-0.051536,0.205140,0.003078,0.158368,0.013016,-0.041488
education_tertiary,-0.068986,-0.012513,0.083069,-0.098019,-0.041987,0.033773,-0.000303,0.022487,-0.001157,-0.095031,...,0.076927,-0.053934,0.604836,-0.051923,0.092210,-0.173470,0.001567,-0.032150,-0.027622,-0.029018
education_unknown,0.073293,0.000959,0.011639,-0.036128,-0.047598,0.002749,-0.003043,0.009791,-0.015684,0.015392,...,0.014314,-0.001286,-0.039941,0.002800,-0.016315,-0.006430,0.061820,-0.016691,-0.014520,0.161987
contact_cellular,-0.068206,-0.002889,0.004086,-0.141946,0.029800,0.034320,0.017624,-0.017733,-0.000474,-0.037623,...,0.005294,-0.014605,0.096847,-0.029112,0.016841,-0.022813,0.011172,0.060406,0.011138,-0.032647
contact_telephone,0.120689,-0.015149,0.029116,-0.059696,-0.001727,0.037242,-0.040379,0.061620,-0.023579,0.046691,...,-0.006114,0.037439,-0.019587,0.044599,0.002289,-0.006797,0.024071,-0.033089,0.013668,0.018699
contact_unknown,0.010386,0.010602,-0.018851,0.177530,-0.030119,-0.054363,0.001928,-0.012468,0.012319,0.015701,...,-0.002439,-0.003592,-0.090874,0.007901,-0.018658,0.027129,-0.023689,-0.046212,-0.018436,0.024566
month_apr,-0.031056,-0.031031,0.017595,0.077911,-0.033307,0.041380,0.043029,-0.078078,-0.022488,-0.004282,...,-0.015902,-0.017634,-0.013772,0.007663,-0.009727,0.003451,0.033544,-0.018876,-0.012744,-0.011658
month_aug,0.088125,-0.005524,0.006746,-0.342784,-0.069545,0.044390,-0.041387,0.176446,-0.028070,0.057786,...,-0.048468,0.035747,0.122926,0.019410,-0.000945,-0.072444,-0.040039,0.152460,-0.038493,0.023668
month_dec,-0.005046,-0.002591,-0.001729,-0.013622,-0.000924,-0.011766,-0.008212,-0.010478,0.006293,-0.008318,...,-0.003440,-0.003014,0.008073,0.003972,-0.003452,-0.001264,-0.002077,0.002846,-0.003038,-0.001386
month_feb,-0.006882,-0.008732,-0.006996,-0.071627,-0.010446,-0.315910,-0.013193,-0.032070,0.000261,-0.039384,...,0.001374,-0.014142,0.001672,0.014736,0.008635,-0.009929,0.033011,-0.006648,0.094230,-0.003500
month_jan,-0.020452,-0.006082,-0.028811,-0.068147,-0.001854,0.270347,0.009830,-0.067323,0.003707,-0.044580,...,-0.004266,-0.004513,0.001439,-0.000197,0.002748,0.004010,0.015091,0.006501,0.053789,0.005986
month_jul,0.015661,0.042667,-0.069231,-0.082669,0.172955,0.163457,0.017831,0.101728,0.014039,0.028754,...,0.025926,0.041836,-0.012785,0.015335,-0.000197,0.026522,-0.030973,-0.020459,-0.007539,-0.012046
month_jun,0.085656,0.008387,0.037525,-0.118060,-0.027232,-0.211740,-0.021173,0.045657,0.014578,0.024260,...,0.015857,0.061572,-0.040023,0.032825,0.011171,0.002672,-0.012943,-0.043945,0.002523,0.058927
month_mar,0.004259,-0.011576,0.017201,-0.055478,-0.022856,-0.013673,-0.010308,-0.008928,-0.007234,-0.016190,...,-0.011980,-0.001942,0.024273,0.023042,-0.000203,-0.016005,0.048395,-0.006793,0.001676,0.001979
month_may,-0.129909,-0.012644,-0.061806,0.420169,-0.050599,-0.046278,0.014137,-0.093437,0.003853,-0.051210,...,-0.017598,-0.072383,-0.085019,-0.047738,-0.034153,0.045593,0.026364,-0.044321,-0.037893,-0.035608
month_nov,0.038068,0.005730,0.138829,-0.005101,0.020236,0.113071,-0.004876,-0.093154,0.009742,0.019610,...,0.052979,-0.014389,0.059065,-0.026414,0.044863,-0.018155,-0.021620,-0.010051,0.018505,-0.011592
month_oct,0.002637,-0.006432,0.026811,-0.005784,0.000207,0.041480,0.011327,-0.026013,0.009622,0.000262,...,0.006657,-0.004040,0.006480,0.003386,0.003551,-0.010966,0.004685,-0.002531,-0.007542,0.003881
job_admin,-0.047348,-0.009384,-0.024774,0.039440,0.025195,-0.008858,-0.008152,-0.020156,0.036940,-0.064991,...,-0.067786,-0.059379,-0.179939,-0.068582,-0.068011,-0.116939,-0.040932,-0.161527,-0.059855,-0.027312
job_blue-collar,-0.028956,0.004706,-0.041461,0.156122,0.005674,-0.035006,0.015951,-0.004635,-0.069165,0.125618,...,-0.105624,-0.092525,-0.280381,-0.106864,-0.105974,-0.182215,-0.063781,-0.251692,-0.093266,-0.042557
job_entrepreneur,0.027956,0.025645,0.011692,0.003303,0.038244,-0.003629,0.000247,-0.002619,-0.000406,0.044941,...,1.000000,-0.031889,-0.096634,-0.036831,-0.036524,-0.062801,-0.021982,-0.086747,-0.032144,-0.014667
job_housemaid,0.084920,0.000017,0.003044,-0.086038,-0.016788,0.005355,-0.007239,0.002804,0.015053,0.046431,...,-0.031889,1.000000,-0.084650,-0.032263,-0.031995,-0.055013,-0.019256,-0.075988,-0.028158,-0.012848
job_management,-0.005302,-0.000951,0.072172,-0.067999,-0.037817,0.026526,-0.010846,0.021105,0.010260,-0.036540,...,-0.096634,-0.084650,1.000000,-0.097769,-0.096955,-0.166707,-0.058352,-0.230271,-0.085328,-0.038935
job_retired,0.333164,-0.003878,0.015917,-0.112274,0.017406,-0.002787,0.001675,-0.013881,0.042143,0.056708,...,-0.036831,-0.032263,-0.097769,1.000000,-0.036953,-0.063539,-0.022240,-0.087765,-0.032522,-0.014840
job_self-employed,0.001712,0.004233,0.015771,-0.032204,-0.008934,0.005080,0.008821,0.004581,-0.018049,0.015806,...,-0.036524,-0.031995,-0.096955,-0.036953,1.000000,-0.063009,-0.022055,-0.087034,-0.032251,-0.014716
job_services,-0.057227,-0.003038,-0.033618,0.062391,0.031939,-0.009461,0.003569,-0.010404,0.018813,-0.015312,...,-0.062801,-0.055013,-0.166707,-0.063539,-0.063009,1.000000,-0.037922,-0.149649,-0.055453,-0.025303
job_student,-0.155146,-0.013429,0.000575,-0.034034,-0.047512,-0.011183,-0.007175,-0.008503,-0.039441,-0.125955,...,-0.021982,-0.019256,-0.058352,-0.022240,-0.022055,-0.037922,1.000000,-0.052382,-0.019410,-0.008857
job_technician,-0.058308,-0.004516,-0.012655,-0.032180,0.008396,0.031902,-0.008469,0.018915,0.013693,-0.073221,...,-0.086747,-0.075988,-0.230271,-0.087765,-0.087034,-0.149649,-0.052382,1.000000,-0.076597,-0.034951
job_unemployed,0.008052,0.007232,0.010020,-0.046197,-0.035591,-0.005475,0.017896,-0.017052,0.008317,-0.011904,...,-0.032144,-0.028158,-0.085328,-0.032522,-0.032251,-0.055453,-0.019410,-0.076597,1.000000,-0.012951
job_unknown,0.043904,-0.006397,0.010672,-0.077605,-0.031734,-0.009526,-0.007971,0.017037,-0.012932,0.014573,...,-0.014667,-0.012848,-0.038935,-0.014840,-0.014716,-0.025303,-0.008857,-0.034951,-0.012951,1.000000

In [20]:
# Generate VIF factors for each feature
vif_scores = pd.DataFrame() 
vif_scores["Attribute"] = features.columns 
  
# calculating VIF for each feature 
vif_scores["VIF Scores"] = [variance_inflation_factor(features.values, i) for i in range(len(features.columns))] 
  
display(vif_scores)

/usr/local/anaconda3/lib/python3.7/site-packages/statsmodels/stats/outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

              Attribute  VIF Scores
0                   age    1.494822
1               default    1.014831
2               balance    1.054258
3               housing    1.419921
4                  loan    1.059531
5                   day    1.445083
6              duration    1.017713
7              campaign    1.131206
8      marital_divorced         inf
9       marital_married         inf
10       marital_single         inf
11    education_primary         inf
12  education_secondary         inf
13   education_tertiary         inf
14    education_unknown         inf
15     contact_cellular         inf
16    contact_telephone         inf
17      contact_unknown         inf
18            month_apr         inf
19            month_aug         inf
20            month_dec         inf
21            month_feb         inf
22            month_jan         inf
23            month_jul         inf
24            month_jun         inf
25            month_mar         inf
26            month_may         inf
27            month_nov         inf
28            month_oct         inf
29            job_admin         inf
30      job_blue-collar         inf
31     job_entrepreneur         inf
32        job_housemaid         inf
33       job_management         inf
34          job_retired         inf
35    job_self-employed         inf
36         job_services         inf
37          job_student         inf
38       job_technician         inf
39       job_unemployed         inf
40          job_unknown         inf

In [70]:
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

target.replace({'yes':1,'no':0}, inplace=True)
summaryTab = []

for col in features:
    logReg = sm.Logit(target, features[col])
    result = logReg.fit(disp=False)
    summaryTab.append([result.pvalues.index[0], result.pvalues.values[0], result.llf])
    
tab = pd.DataFrame(summaryTab, columns=['name','pvalue','llf'])
tab.sort_values(by='llf', ascending=False)

                   name         pvalue           llf
0                   age   0.000000e+00 -10741.096914
5                   day   0.000000e+00 -12907.388431
7              campaign   0.000000e+00 -13314.523946
9       marital_married   0.000000e+00 -16398.383057
3               housing   0.000000e+00 -16583.862880
15     contact_cellular   0.000000e+00 -17972.800393
12  education_secondary   0.000000e+00 -18365.069100
17      contact_unknown   0.000000e+00 -20978.258682
26            month_may   0.000000e+00 -21359.692919
2               balance   0.000000e+00 -22779.045265
6              duration   0.000000e+00 -22950.727929
30      job_blue-collar   0.000000e+00 -23273.984085
13   education_tertiary   0.000000e+00 -23395.829050
10       marital_single   0.000000e+00 -23580.039077
4                  loan   0.000000e+00 -24395.071621
33       job_management   0.000000e+00 -24397.143191
11    education_primary   0.000000e+00 -24738.329005
23            month_jul   0.000000e+00 -24754.960847
38       job_technician   0.000000e+00 -24758.947625
19            month_aug   0.000000e+00 -25225.165817
24            month_jun   0.000000e+00 -25546.214238
8      marital_divorced   0.000000e+00 -25799.462104
29            job_admin   0.000000e+00 -25849.482942
36         job_services   0.000000e+00 -25912.453887
27            month_nov   0.000000e+00 -26059.867561
16    contact_telephone  2.820195e-222 -26714.878664
21            month_feb  2.901121e-215 -26935.108712
14    education_unknown  3.715594e-145 -27023.459640
18            month_apr  2.658536e-215 -27063.314371
22            month_jan   2.046077e-94 -27078.552414
31     job_entrepreneur  2.357067e-133 -27081.000260
35    job_self-employed  5.462616e-137 -27137.215527
32        job_housemaid   8.916553e-99 -27184.229525
34          job_retired  7.406826e-137 -27212.815696
39       job_unemployed  2.104641e-107 -27286.817603
1               default   3.198771e-77 -27350.011273
37          job_student   1.348731e-44 -27589.989796
40          job_unknown   4.001294e-24 -27624.015680
20            month_dec   1.696704e-02 -27720.401771
28            month_oct   4.604379e-02 -27723.844781
25            month_mar   6.184993e-01 -27725.763172

In [49]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                40000
Model:                          Logit   Df Residuals:                    39999
Method:                           MLE   Df Model:                            0
Date:                Fri, 05 Aug 2022   Pseudo R-squ.:                  -1.658
Time:                        14:45:34   Log-Likelihood:                -27624.
converged:                       True   LL-Null:                       -10392.
Covariance Type:            nonrobust   LLR p-value:                       nan
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
job_unknown    -2.5513      0.252    -10.132      0.000      -3.045      -2.058
===============================================================================
"""

In [71]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                40000
Model:                          Logit   Df Residuals:                    39999
Method:                           MLE   Df Model:                            0
Date:                Fri, 05 Aug 2022   Pseudo R-squ.:                  -1.658
Time:                        15:01:00   Log-Likelihood:                -27624.
converged:                       True   LL-Null:                       -10392.
Covariance Type:            nonrobust   LLR p-value:                       nan
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
job_unknown    -2.5513      0.252    -10.132      0.000      -3.045      -2.058
===============================================================================
"""

AttributeError: 'function' object has no attribute 'xname'